// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Protos/dynamiclighting.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Artemis.DynamicLighting {
  /// <summary>
  /// The DynamicLighting service definition
  /// </summary>
  public static partial class DynamicLighting
  {
    static readonly string __ServiceName = "dynamiclighting.DynamicLighting";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Artemis.DynamicLighting.SetDeviceLEDsColorRequest> __Marshaller_dynamiclighting_SetDeviceLEDsColorRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Artemis.DynamicLighting.SetDeviceLEDsColorRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Artemis.DynamicLighting.SetColorResponse> __Marshaller_dynamiclighting_SetColorResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Artemis.DynamicLighting.SetColorResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Artemis.DynamicLighting.GetDevicesStatusRequest> __Marshaller_dynamiclighting_GetDevicesStatusRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Artemis.DynamicLighting.GetDevicesStatusRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Artemis.DynamicLighting.GetDevicesStatusResponse> __Marshaller_dynamiclighting_GetDevicesStatusResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Artemis.DynamicLighting.GetDevicesStatusResponse.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Artemis.DynamicLighting.SetDeviceLEDsColorRequest, global::Artemis.DynamicLighting.SetColorResponse> __Method_SetDeviceLEDsColor = new grpc::Method<global::Artemis.DynamicLighting.SetDeviceLEDsColorRequest, global::Artemis.DynamicLighting.SetColorResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SetDeviceLEDsColor",
        __Marshaller_dynamiclighting_SetDeviceLEDsColorRequest,
        __Marshaller_dynamiclighting_SetColorResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Artemis.DynamicLighting.GetDevicesStatusRequest, global::Artemis.DynamicLighting.GetDevicesStatusResponse> __Method_GetDevicesStatus = new grpc::Method<global::Artemis.DynamicLighting.GetDevicesStatusRequest, global::Artemis.DynamicLighting.GetDevicesStatusResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetDevicesStatus",
        __Marshaller_dynamiclighting_GetDevicesStatusRequest,
        __Marshaller_dynamiclighting_GetDevicesStatusResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Artemis.DynamicLighting.DynamiclightingReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of DynamicLighting</summary>
    [grpc::BindServiceMethod(typeof(DynamicLighting), "BindService")]
    public abstract partial class DynamicLightingBase
    {
      /// <summary>
      /// Sets the color of specific LEDs on a device
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Artemis.DynamicLighting.SetColorResponse> SetDeviceLEDsColor(global::Artemis.DynamicLighting.SetDeviceLEDsColorRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// Gets the status of all connected devices
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Artemis.DynamicLighting.GetDevicesStatusResponse> GetDevicesStatus(global::Artemis.DynamicLighting.GetDevicesStatusRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for DynamicLighting</summary>
    public partial class DynamicLightingClient : grpc::ClientBase<DynamicLightingClient>
    {
      /// <summary>Creates a new client for DynamicLighting</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public DynamicLightingClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for DynamicLighting that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public DynamicLightingClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected DynamicLightingClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected DynamicLightingClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      /// Sets the color of specific LEDs on a device
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Artemis.DynamicLighting.SetColorResponse SetDeviceLEDsColor(global::Artemis.DynamicLighting.SetDeviceLEDsColorRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SetDeviceLEDsColor(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Sets the color of specific LEDs on a device
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Artemis.DynamicLighting.SetColorResponse SetDeviceLEDsColor(global::Artemis.DynamicLighting.SetDeviceLEDsColorRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SetDeviceLEDsColor, null, options, request);
      }
      /// <summary>
      /// Sets the color of specific LEDs on a device
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Artemis.DynamicLighting.SetColorResponse> SetDeviceLEDsColorAsync(global::Artemis.DynamicLighting.SetDeviceLEDsColorRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SetDeviceLEDsColorAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Sets the color of specific LEDs on a device
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Artemis.DynamicLighting.SetColorResponse> SetDeviceLEDsColorAsync(global::Artemis.DynamicLighting.SetDeviceLEDsColorRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SetDeviceLEDsColor, null, options, request);
      }
      /// <summary>
      /// Gets the status of all connected devices
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Artemis.DynamicLighting.GetDevicesStatusResponse GetDevicesStatus(global::Artemis.DynamicLighting.GetDevicesStatusRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetDevicesStatus(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Gets the status of all connected devices
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Artemis.DynamicLighting.GetDevicesStatusResponse GetDevicesStatus(global::Artemis.DynamicLighting.GetDevicesStatusRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetDevicesStatus, null, options, request);
      }
      /// <summary>
      /// Gets the status of all connected devices
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Artemis.DynamicLighting.GetDevicesStatusResponse> GetDevicesStatusAsync(global::Artemis.DynamicLighting.GetDevicesStatusRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetDevicesStatusAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Gets the status of all connected devices
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Artemis.DynamicLighting.GetDevicesStatusResponse> GetDevicesStatusAsync(global::Artemis.DynamicLighting.GetDevicesStatusRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetDevicesStatus, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override DynamicLightingClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new DynamicLightingClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(DynamicLightingBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_SetDeviceLEDsColor, serviceImpl.SetDeviceLEDsColor)
          .AddMethod(__Method_GetDevicesStatus, serviceImpl.GetDevicesStatus).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, DynamicLightingBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_SetDeviceLEDsColor, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Artemis.DynamicLighting.SetDeviceLEDsColorRequest, global::Artemis.DynamicLighting.SetColorResponse>(serviceImpl.SetDeviceLEDsColor));
      serviceBinder.AddMethod(__Method_GetDevicesStatus, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Artemis.DynamicLighting.GetDevicesStatusRequest, global::Artemis.DynamicLighting.GetDevicesStatusResponse>(serviceImpl.GetDevicesStatus));
    }

  }
}
#endregion
